export const SET_RESULT_LOADING = 'SET_RESULT_LOADING'
export const SET_RESULT_SUCCESS = 'SET_RESULT_SUCCESS'
export const SET_RESULT_FAIL = 'SET_RESULT_FAIL'

export const SET_INCORRECT_RESULT_LOADING = 'SET_INCORRECT_RESULT_LOADING'
export const SET_INCORRECT_RESULT_SUCCESS = 'SET_INCORRECT_RESULT_SUCCESS'
export const SET_INCORRECT_RESULT_FAIL = 'SET_INCORRECT_RESULT_FAIL'

export const SET_CORRECT_RESULT_LOADING = 'SET_CORRECT_RESULT_LOADING'
export const SET_CORRECT_RESULT_SUCCESS = 'SET_CORRECT_RESULT_SUCCESS'
export const SET_CORRECT_RESULT_FAIL = 'SET_CORRECT_RESULT_FAIL'